export  const Fir =     {
    'AGGG': 'Solomon Islands',
    'ANAU': 'Nauru',
    'AYPM': 'Papua New Guinea',
    'BGGL': 'Greenland',
    'BIRD': 'Iceland',
    'CZEG': 'Canada',
    'CZQM': 'Canada',
    'CZQX': 'Canada',
    'CZUL': 'Canada',
    'CZVR': 'Canada',
    'CZWG': 'Canada',
    'CZYZ': 'Canada',
    'DAAA': 'Algeria',
    'DGAC': 'Ghana',
    'DIII': 'Ivory Coast',
    'DNKK': 'Nigeria',
    'DRRR': 'Niger',
    'DTTC': 'Tunisia',
    'EZZZ': 'Belgium',
    'EBBU': 'Belgium',
    'EDGG': 'Germany',
    'EDMM': 'Germany',
    'EDUU': 'Germany',
    'EDVV': 'Germany',
    'EDWW': 'Germany',
    'EDYY': 'Belgium, Germany, Netherlands',
    'EETT': 'Estonia',
    'EFIN': 'Finland',
    'EGGX': 'UK',
    'EGPX': 'UK',
    'EGQQ': 'UK',
    'EGTT': 'UK',
    'EHAA': 'Netherlands',
    'EISN': 'Ireland',
    'EKDK': 'Denmark',
    'ENOB': 'Norway',
    'ENOR': 'Norway',
    'EPWW': 'Poland',
    'ESAA': 'Sweden',
    'ESMM': 'Sweden',
    'ESOS': 'Sweden',
    'EVRR': 'Latvia',
    'EYVL': 'Lithuania',
    'FABL': 'South Africa',
    'FACA': 'South Africa',
    'FACT': 'South Africa',
    'FADN': 'South Africa',
    'FAJO': 'South Africa',
    'FAJX': 'South Africa',
    'FAPX': 'South Africa',
    'FBGR': 'Botswana',
    'FCCC': 'Congo Brazzaville',
    'FIMM': 'Mauritius',
    'FKKK': 'Cameroon',
    'FLFI': 'Zambia',
    'FMCX': 'Comoros',
    'FMMM': 'Madagascar',
    'FNAN': 'Angola',
    'FOOO': 'Gabon',
    'FQBE': 'Mozambique',
    'FSSS': 'Seychelles',
    'FTTT': 'Chad',
    'FVHF': 'Zimbabwe',
    'FWLL': 'Malawi',
    'FYWF': 'Namibia',
    'FZZA': 'Congo DRC',
    'GCCC': 'Spain',
    'GLRB': 'Liberia',
    'GMMM': 'Morocco',
    'GOOO': 'Senegal',
    'GVSC': 'Cape Verde',
    'HAAA': 'Ethiopia',
    'HBBA': 'Burundi',
    'HCSM': 'Somalia',
    'HECC': 'Egypt',
    'HHAA': 'Egypt',
    'HKNA': 'Kenya',
    'HLLL': 'Libya',
    'HRYR': 'Rwanda',
    'HSSX': 'Sudan',
    'HTDC': 'Tanzania',
    'HUEC': 'Uganda',
    'KZAB': 'USA',
    'KZAK': 'USA',
    'KZAU': 'USA',
    'KZBW': 'USA',
    'KZDC': 'USA',
    'KZDV': 'USA',
    'KZFW': 'USA',
    'KZHU': 'USA',
    'KZID': 'USA',
    'KZJX': 'USA',
    'KZKC': 'USA',
    'KZLA': 'USA',
    'KZLC': 'USA',
    'KZMA': 'USA',
    'KZME': 'USA',
    'KZMP': 'USA',
    'KZNY': 'USA',
    'KZOA': 'USA',
    'KZOB': 'USA',
    'KZSE': 'USA',
    'KZTL': 'USA',
    'KZWY': 'USA',
    'LAAA': 'Albania',
    'LBSR': 'Bulgaria',
    'LBWR': 'Bulgaria',
    'LCCC': 'Cyprus',
    'LDZO': 'Croatia',
    'LECB': 'Spain',
    'LECM': 'Spain',
    'LECS': 'Spain',
    'LFBB': 'France',
    'LFEE': 'France',
    'LFFF': 'France',
    'LFMM': 'France',
    'LFRR': 'France',
    'LGGG': 'Greece',
    'LHCC': 'Hungary',
    'LIBB': 'Italy',
    'LIMM': 'Italy',
    'LIRR': 'Italy',
    'LJLA': 'Slovenia',
    'LKAA': 'Czech Republic',
    'LLLL': 'Israel',
    'LMMM': 'Malta',
    'LOVV': 'Austria',
    'LPPC': 'Portugal',
    'LPPO': 'Portugal',
    'LQSB': 'Bosnia and Herzegovina',
    'LRBB': 'Romania',
    'LSAG': 'Switzerland',
    'LSAS': 'Switzerland',
    'LSAZ': 'Switzerland',
    'LTAA': 'Turkey',
    'LTBB': 'Turkey',
    'LUUU': 'Moldova',
    'LWSS': 'North Macedonia',
    'LYBA': 'Serbia',
    'LZBB': 'Slovakia',
    'MDCS': 'Dominican Republic',
    'MHTG': 'Honduras',
    'MKJK': 'Jamaica',
    'MMFO': 'Mexico',
    'MMFR': 'Mexico',
    'MPZL': 'Panama',
    'MTEG': 'Haiti',
    'MUFH': 'Cuba',
    'MYNA': 'Bahamas',
    'NFFF': 'Fiji',
    'NTTT': 'French Polynesia',
    'NWWX': 'New Caledonia',
    'NZZC': 'New Zealand',
    'NZZO': 'New Zealand',
    'OAKX': 'Afghanistan',
    'OBBB': 'Bahrain',
    'OEJD': 'Saudi Arabia',
    'OIIX': 'Iran',
    'OJAC': 'Jordan',
    'OKAC': 'Kuwait',
    'OLBB': 'Lebanon',
    'OMAE': 'United Arab Emirates',
    'OOMM': 'Oman',
    'OPKR': 'Pakistan',
    'OPLR': 'Pakistan',
    'ORBB': 'Iraq',
    'ORMM': 'Iraq',
    'OSTT': 'Syria',
    'OYSC': 'Yemen',
    'PAZA': 'USA',
    'PAZN': 'USA',
    'PHZH': 'USA',
    'RCAA': 'Taiwan',
    'RJJJ': 'Japan',
    'RKRR': 'South Korea',
    'RPHI': 'Philippines',
    'SACF': 'Argentina',
    'SACU': 'Argentina',
    'SAEF': 'Argentina',
    'SAEU': 'Argentina',
    'SAMF': 'Argentina',
    'SAMV': 'Argentina',
    'SARR': 'Argentina',
    'SAVF': 'Argentina',
    'SAVU': 'Argentina',
    'SBAO': 'Brazil',
    'SBAZ': 'Brazil',
    'SBBS': 'Brazil',
    'SBCW': 'Brazil',
    'SBRE': 'Brazil',
    'SCCZ': 'Chile',
    'SCEZ': 'Chile',
    'SCFZ': 'Chile',
    'SCIZ': 'Chile',
    'SCTZ': 'Chile',
    'SEFG': 'Ecuador',
    'SGFA': 'Paraguay',
    'SKEC': 'Colombia',
    'SKED': 'Colombia',
    'SLLF': 'Bolivia',
    'SMPM': 'Suriname',
    'SOOO': 'French Guiana',
    'SPIM': 'Peru',
    'SUEO': 'Uruguay',
    'SVZM': 'Venezuela',
    'SYGC': 'Guyana',
    'TJZS': 'USA',
    'TNCF': 'Netherlands Antilles',
    'TTZP': 'Trinidad and Tobago',
    'UAAX': 'Kazakhstan',
    'UACX': 'Kazakhstan',
    'UAFX': 'Kyrgyzstan',
    'UASS': 'Kazakhstan',
    'UDDD': 'Armenia',
    'UEMH': 'Russia',
    'UENN': 'Russia',
    'UESS': 'Russia',
    'UESU': 'Russia',
    'UEVV': 'Russia',
    'UGEE': 'Russia',
    'UGGG': 'Georgia',
    'UHBI': 'Russia',
    'UHMI': 'Russia',
    'UHMP': 'Russia',
    'UHNN': 'Russia',
    'UHPT': 'Russia',
    'UHPU': 'Russia',
    'UHSH': 'Russia',
    'UIKB': 'Russia',
    'UIKK': 'Russia',
    'UKBV': 'Ukraine',
    'UKCV': 'Ukraine',
    'UKDV': 'Ukraine',
    'UKFV': 'Ukraine',
    'UKHV': 'Ukraine',
    'UKLV': 'Ukraine',
    'UKOV': 'Ukraine',
    'ULLL': 'Russia',
    'ULOL': 'Russia',
    'UMKD': 'Russia',
    'UMMV': 'Belarus',
    'UNLL': 'Russia',
    'UOTT': 'Russia',
    'URRV': 'Russia',
    'USDK': 'Russia',
    'USHB': 'Russia',
    'USHH': 'Russia',
    'UTAK': 'Turkmenistan',
    'UTNR': 'Uzbekistan',
    'UTSD': 'Uzbekistan',
    'UTTR': 'Uzbekistan',
    'UUWV': 'Russia',
    'UUYW': 'Russia',
    'UUYY': 'Russia',
    'UWOO': 'Russia',
    'VABF': 'India',
    'VCCC': 'Sri Lanka',
    'VECF': 'India',
    'VGFR': 'Bangladesh',
    'VHHK': 'Hong Kong',
    'VIDF': 'India',
    'VLIV': 'Laos',
    'VLVT': 'Laos',
    'VNSM': 'Nepal',
    'VOMF': 'India',
    'VRMF': 'Maldives',
    'VTBB': 'Thailand',
    'VVTS': 'Vietnam',
    'VVVV': 'Vietnam',
    'VYMD': 'Myanmar',
    'VYYF': 'Myanmar',
    'WAAF': 'Indonesia',
    'WAAZ': 'Indonesia',
    'WABZ': 'Indonesia',
    'WADZ': 'Indonesia',
    'WAJZ': 'Indonesia',
    'WAKZ': 'Indonesia',
    'WALZ': 'Indonesia',
    'WAMZ': 'Indonesia',
    'WAOZ': 'Indonesia',
    'WAPZ': 'Indonesia',
    'WATZ': 'Indonesia',
    'WBFC': 'Brunei / Malaysia',
    'WIIF': 'Indonesia',
    'WIIZ': 'Indonesia',
    'WIMZ': 'Indonesia',
    'WIOZ': 'Indonesia',
    'WIPZ': 'Indonesia',
    'WMFC': 'Malaysia',
    'WSJC': 'Singapore',
    'YBBB': 'Australia',
    'YMMM': 'Australia',
    'ZBPE': 'China Mainland',
    'ZGJD': 'China Mainland',
    'ZGZU': 'China Mainland',
    'ZHWH': 'China Mainland',
    'ZJSA': 'China Mainland',
    'ZKKP': 'North Korea',
    'ZLHW': 'China Mainland',
    'ZMUB': 'Mongolia',
    'ZPKM': 'China Mainland',
    'ZSHA': 'China Mainland',
    'ZWUQ': 'China Mainland',
    'ZYSH': 'China Mainland',

}
